SELECT /*+ RULE */ l.FLOW_TYPE, p.KOD_POINT, o.KOD_NUMOBJ, r.RASX_TIPRASX, 
    R.RASX_01, R.RASX_02, R.RASX_03, R.RASX_04, R.RASX_05, R.RASX_06, R.RASX_07, R.RASX_08, R.RASX_09, R.RASX_10, R.RASX_11, R.RASX_12
    FROM IER_LINK_OBJECTS l, HR_POINT p, KR_NUMOBJ o, SIO_RASX r
    WHERE l.ID_IES =  :pnt_ies
    AND p.KOD_POINT = l.ID
    AND o.KOD_OBJ = p.KOD_OBJ
    AND r.PNT_KOD_POINT (+) = l.ID_IES
