begin
    IEG_ISE_POINT.insorupd_pointhar_(
        kod_point_ => :kod_point_,
        kod_numobj_ => :kod_numobj_,
        dat_s_ => :dat_s_,
        dat_po_ => :dat_po_,
        method_ => :method_,
        var_losses_val_ => :var_losses_val_,
        tar_pricegroup_ => :tar_pricegroup_,
        tar_voltage_ => :tar_voltage_,
        tar_consgroup_ => :tar_consgroup_,
        tar_region_ => :tar_region_,
        rasx_tiprasx_ => :rasx_tiprasx_,
        rasx_01_ => :rasx_01_,
        rasx_02_ => :rasx_02_,
        rasx_03_ => :rasx_03_,
        rasx_04_ => :rasx_04_,
        rasx_05_ => :rasx_05_,
        rasx_06_ => :rasx_06_,
        rasx_07_ => :rasx_07_,
        rasx_08_ => :rasx_08_,
        rasx_09_ => :rasx_09_,
        rasx_10_ => :rasx_10_,
        rasx_11_ => :rasx_11_,
        rasx_12_ => :rasx_12_,
        flow_type_ => :flow_type_,
        st_ => :st_,
        errM_ => :errM_
    );
end;