DECLARE
    code INT;
    msg VARCHAR2(1000);
BEGIN
    DELETE FROM SIO_MDM_LOG WHERE tran_id = 100;
    COMMIT;

    IEG_CONTROLLER.RUN(code, MSG);
    DBMS_OUTPUT.PUT_LINE(CURRENT_TIMESTAMP||' '||CODE||' '||MSG);
    IEG_CONTROLLER.RUN(code, MSG);
    DBMS_OUTPUT.PUT_LINE(CURRENT_TIMESTAMP||' '||CODE||' '||MSG);
END;