SELECT /*+ ORDERED */ p.KOD_POINT, o.KOD_NUMOBJ, l.FLOW_TYPE
  FROM IER_LINK_OBJECTS l, HR_POINT p, KR_NUMOBJ o
 WHERE l.ID_IES = :PNT_KOD_POINT
   AND l.ID = p.KOD_POINT
   AND o.KOD_OBJ = p.KOD_OBJ
   AND o.PR_ACTIVE != 1
